[book]
authors = ["lzzsG"]
language = "zh"
multilingual = false
src = "src"
title = "RUST Real-world Interface"

[output.html]
default-theme = "black"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/lzzsG/rust-real-world-interface"
preferred-dark-theme = "black"
site-url = "/rust-real-world-interface/"

[output.html.playground]
editable = true
